import Navbar from '@/components/Navbar';
import './globals.css';
import { Inter } from 'next/font/google';
import Providers from './Providers';
import Moviebar from '@/components/Moviebar';
import Searchbox from '@/components/Searchbox';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'IMDb',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body id="main-body" className={inter.className}>
        <Providers>
          <Navbar />
          <Moviebar />
          <Searchbox />
          {children}
        </Providers>
      </body>
    </html>
  );
}
